name: Python test

on:
  push:
  pull_request:
    branches: ["*"]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4.5.0
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest
  build:
    runs-on: windows-latest
    needs: test
    if: ${{ needs.test.result == 'success' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.10"
      
      - name: Install dependecies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller 
        
      - name: Build executable
        run: pyinstaller --onefile window.py

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: window
          path: dist/window.exe
    
